FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY . .
# THÊM CÁC PARAMETERS ĐỂ BỎ QUA WARNINGS
RUN dotnet restore "DMS.sln" --verbosity minimal --ignore-failed-sources
RUN dotnet publish "DMS.Presentation/DMS.Presentation.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app/publish .
ENV ASPNETCORE_URLS=http://0.0.0.0:10000
ENV ASPNETCORE_ENVIRONMENT=Production
ENTRYPOINT ["dotnet", "DMS.Presentation.dll"]